config/routes.rb
Task3::Application.routes.draw do

  root :to => 'articles#index'

     get 'products' => 'catalog#view', as: :catalogue
     get 'profile' => 'articles#profile', as: :profile
     get 'contact' => 'articles#contact', as: :contact

     resources :articles
     resources :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

  end
  
  def profile
    @profile_name = "Ahsan Malik"
    @jenkel = "Pria"
    @tempat = "Bandung"
    @ttl = "1 Januari 1900"
    @alamat = "Padalarang, Kab. Bandung Barat 40553, Indonesia"
  end
  
  def contact
    @contact_name = "Ahsan Malik"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/contact.html.erb
<h1><%= @contact_name%> Contact</h1>

<!-- Content  -->
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h1> <%= @contact_name%></h1>
          	<%= image_tag("profile2.JPG", alt: "Image Pgofile", width: "140px", height: "140px", class: "img-circle") %>
          	
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
         	<%= form_tag("#", class: "form-horizontal") do %>
         		<div class="form-group">
         			<%= label_tag "inputEmail", "Email", class: "col-sm-2 control-label"%>
         			<div class="col-sm-10">
         				<%= text_field "person", "email", "id" => "inputEmail", "class" => "form-control", "placeholder" => "Email" %>
         			</div>
         		</div>
         		<div class="form-group">
         			<%= label_tag "inputMessage", "Messages", class: "col-sm-2 control-label" %>
         			<div class="col-sm-10">
         				<%= text_area "post", "messages", "rows" => 20, class: "form-control", placeholder: "Leave a messages" %>
         			</div>
         		</div>
         		<div class="form-group">
         			<div class="col-sm-10">
         				<%= button_tag "Send a Messages", class: "btn btn-default" %>
         			</div>
         		</div>
         	<% end %>
         </div>
        </div>
      </div>
    </div>

app/views/articles/index.html.erb
<h1 >Welcome</h1>

<!-- Content  -->
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
    <li data-target="#carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("1.jpg", alt: "Gambar Satu") %>
      <div class="carousel-caption">
        <h1>Gambar Satu</h1>
      </div>
    </div>
    <div class="item">
      <%= image_tag("2.jpg", alt: "Gambar Dua") %>
      <div class="carousel-caption">
        <h1>Gambar Dua</h1>
      </div>
    </div>
    <div class="item">
      <%= image_tag("3.jpg", alt: "Gambar Tiga")%>
      <div class="carousel-caption">
        <h1>Gambar Tiga</h1>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div>Hello saya Ahsan dan saya saat ini akan lulus dari kuliah, salam kenal ya. berikut contoh dari hasil design grafik yang saya buat.</div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div>
			<p>Facebook: sann.lix@mail.com</p>
            <p>Twitter: tidak ada</p>
            <p>Telp: 022-6806923</p>
            <p>Alamat: Padalarang - Kab. Bandung Barat 40553, Indonesia</p>
          </div>
        </div>
      </div>
    </div>

app/views/articles/profile.html.erb
<h1><%= @profile_name%> Profile</h1>

<!-- Content  -->
<div class="container clearfix">
      <div class="row row-offcanvas row-offcanvas-left ">
        <!--Bagian Kiri-->
        <div class="col-xs-12 col-sm-3 side pull-left sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
          	<h1> <%= @profile_name %> </h1>
          	<%= image_tag("profile2.JPG", alt: "Image Pgofile", width: "140px", height: "140px", class: "img-circle") %>
          	
          </div>
        </div>

        <!--Bagian Kanan-->
        <div id="main-content" class="col-xs-12 col-sm-9 main pull-right">
         <div class="panel-body">
         	<table class="table table-hover table-striped display">
         		<tbody>
         			<tr>
         				<th>Nama</th>
         				<td><%= @profile_name %></td>
         			</tr>
         			<tr>
         				<th>Tempat, Tanggal Lahir</th>
         				<td><%= @tempat +", "+ @ttl %></td>
         			</tr>
         			<tr>
         				<th>Jenis Kelamin</th>
         				<td><%= @jenkel %></td>
         			</tr>
         			<tr>
         				<th>Alamat Domisili</th>
         				<td><%= @alamat %></td>
         			</tr>
         		</tbody>
         	</table>
         </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE-edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Task 3</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body style="padding-top: 60px;">
<!-- Navigation -->
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collape" data-targer=".navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar" />
				<span class="icon-bar" />
				<span class="icon-bar" />
			</button>
			<span class="navbar-brand"><%= link_to 'Task 3', articles_path %></span>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', articles_path %></li>
				<li><%= link_to 'Profile', profile_path %></li>
				<li><%= link_to 'Contact', contact_path %></li>
			</ul>
		</div>
	</div>
</div>

<%= yield %>

</body>
</html>